# Generated by Django 3.0.4 on 2020-04-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200415_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='company',
            new_name='company_id',
        ),
    ]
