# Generated by Django 3.0.4 on 2020-04-15 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200415_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='company_id',
            new_name='company',
        ),
    ]
